### ISSUE TITLE
Server for hosting static files

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#61]
>**Migrated from Trello**

- [X]  ~~Docker container for uploading  static files (_build/html folder) (to a server)~~

- [X] ~~Server for static file management~~
- [X] ~~flask+uWSGI+nginx implementation~~
- [ ] actions to avoid uploading duplicated files in the server
- [ ] The function to decide the files to upload

----
**Comments**
>**Qianqian Qin:**
 To decide files to upload, the function might be improved in the future

**Comment by raphendyr** [comment]
PR working on this: #38

**Comment by jaguarfi** [comment]
It could be benefitial to link the issue in the PR. 
P.S. I already linked the issue to the PR #38

**Comment by jaguarfi** [comment]
Also, this issue should be moved from the "New and unsorted" list  to the "In progress" list

**Comment by raphendyr** [comment]
Other related project (static file side). https://github.com/apluslms/static-file-host while #38 focuses on the non-static data with same library

**Comment by jaguarfi** [comment]
@raphendyr should we close this PR?

**Comment by raphendyr** [comment]
Apaprently the PR was missing a link to the issue, so it wasn't automatically closed.
